// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug logging to help identify environment variable issues
console.log('Environment variables check:', {
  SUPABASE_URL: SUPABASE_URL ? 'Set' : 'Missing',
  SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? 'Set' : 'Missing',
  env: import.meta.env
});

if (!SUPABASE_URL) {
  throw new Error('VITE_SUPABASE_URL environment variable is required but not set');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('VITE_SUPABASE_ANON_KEY environment variable is required but not set');
}

// Cookie domain should be .biblenow.io in production
// This allows auth sharing across subdomains (auth.biblenow.io and social.biblenow.io)
const cookieDomain = window.location.hostname.includes('biblenow.io') 
  ? '.biblenow.io' 
  : window.location.hostname;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Use PKCE flow for better security
    debug: true, // Enable debug mode for troubleshooting
    storage: {
      getItem: (key) => document.cookie.match(`(^|;)\\s*${key}\\s*=\\s*([^;]+)`)?.pop() || '',
      setItem: (key, value) => {
        document.cookie = `${key}=${value}; domain=${cookieDomain}; path=/; max-age=2592000; SameSite=Lax; secure`;
      },
      removeItem: (key) => {
        document.cookie = `${key}=; domain=${cookieDomain}; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; SameSite=Lax; secure`;
      },
    },
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
  },
});
